### ISSUE TITLE
Error on 2.0.4 patch

### ISSUE THREAD

**Issue by Beatgrim2997** [roema/cryptsetup-nuke#2]
1 of 16 tests failed
(5 tests were not run)
make[3]: *** [Makefile:752: check-TESTS] Error 1
make[3]: Leaving directory '/home/tooltoulto/cryptsetup-2.0.4/tests'
make[2]: *** [Makefile:879: check-am] Error 2
make[2]: Leaving directory '/home/tooltoulto/cryptsetup-2.0.4/tests'
make[1]: *** [Makefile:2293: check-recursive] Error 1
make[1]: Leaving directory '/home/tooltoulto/cryptsetup-2.0.4'
dh_auto_test: make -j8 check VERBOSE=1 returned exit code 2
make: *** [debian/rules:18: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

###error point###

CASE: Image in file tests (root capabilities not required)
[1] format
[2] open
[3] add key
[4] change key
[5] remove key
[6] kill slot
[7] header backup
[8] header restore
[9] luksDump
[10] uuid
CASE: [1] open - compat image - acceptance check
CASE: [2] open - compat image - denial check
CASE: [3] format
CASE: [4] format using hash sha512
CASE: [5] open
CASE: [6] add key
CASE: [7] unsuccessful delete
CASE: [8] successful delete
CASE: [9] add key test for key files
CASE: [10] delete key test with key1 as remaining key
CASE: [11] delete last key
CASE: [12] parameter variation test
CASE: [13] open/close - stacked devices
CASE: [14] format/open - passphrase on stdin & new line
CASE: [15] UUID - use and report provided UUID
CASE: [16] luksFormat
CASE: [17] AddKey volume key, passphrase and keyfile
Failed to read from key storage.

No key available with this passphrase.
FAILED at line 409 ./compat-test
FAIL: compat-test
CASE: [3] format
CASE: [4] format using hash sha512
CASE: [5] open
CASE: [6] add key
CASE: [7] unsuccessful delete
CASE: [8] successful delete
CASE: [9] add key test for key files
CASE: [10] delete key test with key1 as remaining key
CASE: [11] delete last key
CASE: [12] parameter variation test
CASE: [13] open/close - stacked devices
CASE: [14] format/open - passphrase on stdin & new line
CASE: [15] UUID - use and report provided UUID
CASE: [16] luksFormat
CASE: [17] AddKey volume key, passphrase and keyfile
CASE: [18] RemoveKey passphrase and keyfile
CASE: [19] create & status & resize
CASE: [20] Disallow open/create if already mapped.
CASE: [21] luksDump
CASE: [22] remove disappeared device
CASE: [23] ChangeKey passphrase and keyfile
CASE: [24] Keyfile limit
CASE: [25] Create shared segments
CASE: [26] Suspend/Resume
CASE: [27] luksOpen with specified key slot number
CASE: [28] Detached LUKS header
CASE: [29] Repair metadata
CASE: [30] LUKS erase
CASE: [31] LUKS convert
CASE: [32b] LUKS2 key in keyring
CASE: [33] tokens
Cannot find keyctl, test skipped
SKIP: compat-test2
WARNING: test require uuencode binary, test skipped.
SKIP: loopaes-test

Cannot find keyctl, test skipped
SKIP: keyring-test
Cannot find keyctl, test skipped
SKIP: keyring-compat-test
Cannot find jq, test skipped.
SKIP: luks2-validation-test

**Comment by roema** [comment]
Sorry, i have tested on fresh Ubuntu 18.10 installation and it works fine. If you have problems, please post your steps.
